---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
```


```{r}
data(starwars) 
# taking the starwar dataset:

# from that we will use height,weight to calculate BMI for just human species and not droid species for different genders and just omit rows that have a missing value in any column

starwars %>% 
  select(height,mass, gender,species) %>% 
  filter(species=="Human") %>% 
  na.omit() %>% 
  mutate(height = height/100) %>% 
  mutate( BMI = round(mass/height^2)) %>% 
  group_by(gender) %>% 
  summarise(Average_BMI = mean(BMI))
```


```{r}
# types of data
# Creating a dataframe

name <- c("Person1", "Person2","Person3","Person4","Person5","Person6","Person7")
height <- c("Short","Tall","Medium","Short","Medium","Tall","Short")
age <- c(23,24,26,22,28,19,25)
weight <- c(76.2,60.3,58,79.5,56.2,45,90.3)

friends <- data.frame(name,height,age,weight)

str(friends)
# so now we can let name be a chr but the height is in 3 levels "Short ,medium,tall" so we want it to be a factor

friends$height <- as.factor(friends$height)
str(friends)

levels(friends$height)
# the output is medium short tall but we want it as short medium tall so

friends$height <- factor(friends$height ,
                         levels= c("Short","Medium","Tall"))
levels(friends$height)


# converting age from num to int
friends$age <- as.integer(friends$age)
class(friends$age)


# prints column of age
friends$age 

# prints true false
friends$age >23

friends <- friends

# adding new column
friends$old <- friends$age >23

str(friends)
```


```{r}
# rename and reorder columns

data(starwars)
copy <- starwars %>% 
  select(name, height, mass, hair_color) %>% 
  rename(weight =mass)

#the order of columns you give here the copy will have it in that particular order

copy


```


```{r}
#recoding our data (dividing height/100 and renaming genders as m and f)
copy <- starwars %>% 
  select(name,height,mass,gender) %>% 
  rename(weight = mass) %>% 
  na.omit() %>% 
  mutate(height = height/100) %>% 
  filter(gender == "masculine" | gender =="feminine") %>% 
  mutate(gender = recode(gender,
                         masculine = "m",
                         feminine = "f")) %>% 
  mutate(size = height >1 & weight >75,
         size = if_else(size==TRUE, "Big", "Small"))

#filter(gender %in% c("masculine", "feminine"))  another way to use filter
#if size = true then put big else small
```


```{r}
# ways to filter your Data

view(msleep)

#arranging using certain columns

data <- msleep %>% 
    select(name, order, sleep_total) %>%
    arrange(sleep_total)

summary_data <- msleep %>% 
    summarise(avg_sleep = mean(sleep_total), 
              min_sleep = min(sleep_total),
              max_sleep = max(sleep_total),
              total = n())





#1
mydata <- msleep %>% 
  select(name , sleep_total) %>% 
  filter(sleep_total>18)

#2
mydata <- msleep %>% 
  select(name , sleep_total) %>% 
  filter(!sleep_total>18)

#3
mydata <- msleep %>% 
  select(name, order, bodywt, sleep_total) %>% 
  filter(order == "Primates", bodywt>20)

#4
mydata <- msleep %>% 
  select(name, order, bodywt, sleep_total) %>% 
  filter(order == "Primates"| bodywt>20)

#5
mydata <- msleep %>% 
  select(name,sleep_total) %>% 
  filter(name %in% c("Cow", "Dog","Goat"))

#6 Values bw 16 and 18
mydata <- msleep %>% 
  select(name, sleep_total) %>% 
  filter(between(sleep_total,16,18))

#7 Values at 0.5 distance from 17
mydata <- msleep %>% 
  select(name, sleep_total) %>% 
  filter(near(sleep_total,17,tol= 0.5))

#8 Missing values in conservation
mydata <- msleep %>% 
  select(name, conservation, sleep_total) %>% 
  filter(is.na(conservation))


#9 print data with missing values and modify them

mydata <- msleep %>% 
  select(name, conservation, sleep_total) %>% 
  filter(is.na(conservation)) 

#and then replace it with string 0 or int 0 depending on the datatype of your column 
#column/dataset name[is,na(column/dataset name)] = "string"/value

mydata$conservation[is.na(mydata$conservation)]="0"



```


```{r}

# using functions and objects

#creating an object
my_age <- 21
your_age <- 22

sum(my_age,your_age)

#new dataset
view(cars)
plot(cars)
hist(cars$speed)
#attach(cars)  
#after this you dont have to do dataset$column_name just use column names

summary(cars)

summary(cars$speed)

class(cars)

class(cars$speed)

length(cars$speed)

n_distinct(cars$speed) #count of unique values

unique(cars$speed)  #print those values

head(cars)

tail(cars)

class(cars$speed)

#arranging it in ascending order

arranged_data <-cars %>% 
  select(speed) %>% 
  arrange(cars$speed)


#arranging in descending order

arranged_data <-cars %>% 
  select(speed) %>% 
  arrange(desc(cars$speed))




#subset of data dataset[rows,columns]
cars[1:3,1:2]


# to find out about a function ?function_name
?median
median(cars$dist)

?sort


#creating a object with missing values
new_data <- c(2,3,4,6,NA,9)
sort(new_data,decreasing=FALSE)  #ascending order
sort(new_data,decreasing=TRUE)   #descending order

median(new_data) #the output will be NA
median(new_data, na.rm=TRUE) #the output will be median
```




```{r}
data(starwars)


#operations on missing vaues


#it will omit rows which have missing value in any column
starwars %>% 
  select(name,gender,hair_color,height) %>% 
  na.omit()


#rows which have missing value in at-least 1 column
starwars %>% 
  select(name,gender,hair_color,height) %>% 
  filter(!complete.cases(.))

view(starwars)

#drop rows where missing values are in height column
starwars %>% 
  select(name,gender,hair_color,height) %>% 
  drop_na(height)

#replace missing value in haircolor with "none"

starwars$hair_color[is.na(starwars$hair_color)] = "none"

#or  

starwars %>% 
  select(name,gender,hair_color,height) %>% 
  filter(!complete.cases(.)) %>% 
  mutate(hair_color = replace_na(hair_color,"none"))
```



```{r}

#Deal with duplicates

Names <- c("Ram", "Shyam", "Ram")
Age <- c(25,21,25)

test_data <- data.frame(Names,Age)

#check for duplicates using
duplicated(test_data)
#output will be true false

#print dataframe without duplicates

test_data[!duplicated(test_data), ]

#or use this

test_data <- test_data %>% distinct()
test_data
```



